import 'dart:io';

import 'package:cached_network_image/cached_network_image.dart';
import 'package:critt_v2/core/model/models.dart';
import 'package:critt_v2/core/providers/providers.dart';
import 'package:critt_v2/core/utils/clipboard.dart';
import 'package:critt_v2/core/utils/currency_utils.dart';
import 'package:critt_v2/ui/constants/constants.dart';
import 'package:critt_v2/ui/screens/screens.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:image_picker/image_picker.dart';
import 'package:liquid_pull_to_refresh/liquid_pull_to_refresh.dart';

import 'package:provider/provider.dart';

part 'transaction/list_transaction.dart';
part 'transaction/detail_transaction.dart';
part 'transaction/detail_receiver.dart';
part 'transaction/helper_confirm_transaction.dart';
part 'main_screen/card_verified.dart';
part 'refund/list_history_withdraw.dart';
part 'refund/list_history_refund.dart';
part 'refund/menu_refund.dart';
part 'refund/btn_request_refund.dart';
part 'refund/show_receipt.dart';
part 'receiver/list_last_receiver.dart';
part 'dialog/invoice_dialog.dart';
part 'btn_bantuan.dart';
part 'dash_sparator.dart';
part 'garis_pemisah.dart';
part 'btn_salin.dart';
part 'bank_selected.dart';
part 'dialog/custom_info_dialog.dart';
part 'dialog/info_dialog.dart';
part 'dialog/loading_dialog.dart';
part 'dialog/pick_image_dialog.dart';
